In [1]:
import numpy as np

In [2]:
my_list_1= [1,2,3,4]
my_array_1= np.array(my_list_1)
my_array_1

array([1, 2, 3, 4])

In [3]:
my_list_2 = [11,22,33,44]

Multi-dimensional array

In [4]:
my_lists = [my_list_1,my_list_2]
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [5]:
my_array2.shape

(2, 4)

In [6]:
my_array2.dtype

dtype('int32')

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
my_zeros_array = np.zeros(5)
my_zeros_array.dtype

dtype('float64')

In [9]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.empty(3)

array([2.37663529e-312, 2.14321575e-312, 9.76154329e-313])

In [13]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arange(5,20,3)

array([ 5,  8, 11, 14, 17])