Using arrays and scalars

In [1]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
from __future__ import division
5/2

2.5

In [4]:
arr1= np.array([[1,2,3,4],[8,9,10,11]])

In [5]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [6]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

Indexing arrays

In [7]:
arr_1= np.arange(0,11)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr_1[8]

8

In [9]:
arr_1[1:5]

array([1, 2, 3, 4])

In [10]:
arr_1[0:5]=100
arr_1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr_2d = np.array(([1,2,3,4],[5,67,8,9],[23,4,5,6]))
arr_2d

array([[ 1,  2,  3,  4],
       [ 5, 67,  8,  9],
       [23,  4,  5,  6]])

In [12]:
arr_2d.shape

(3, 4)

In [13]:
arr_2d[0] #first row

array([1, 2, 3, 4])

In [14]:
arr_2d[:2,1:]

array([[ 2,  3,  4],
       [67,  8,  9]])


Array Transposition



In [15]:
arr_t = np.arange(50).reshape((10,5))
arr_t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [16]:
arr_t.T # transpose

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [17]:
np.dot(arr_t.T,arr_t)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [18]:
arr_3d = np.arange(50).reshape((5,5,2))
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [20]:
arrN = np.array([[1,2,3]])
arrN

array([[1, 2, 3]])

In [21]:
arrN.swapaxes(0,1) # interchanges axes

array([[1],
       [2],
       [3]])